name:               "TheFireRed"
description:        "A translator's emotional garbage dump."

url:                "https://thefirered.github.com"
author:             "TheFireRed"
gravatar_hash:      "CDF0285DC211EC5C09FCB5FFF437D9FF"
twitter:            "TheFireRed"
email:              ""
github:             ""
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   ""

background:         ""

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"


sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
